version: '3.8'


services:
  web:
    build: .
    command: "uvicorn app.main:app --reload --host '0.0.0.0'"
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - local
    depends_on:
      - postgres
      
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file:
      - ".env.docker"
    networks:
      - local


networks:
  local:
  
volumes:
  postgres_data: