"""added auth0 auth flag

Revision ID: 02758c395092
Revises: e641084f2801
Create Date: 2023-07-20 12:12:33.180050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02758c395092'
down_revision = 'e641084f2801'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_registered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth0_registered')
    # ### end Alembic commands ###
