"""add completion time to quiz

Revision ID: 0d28b3ebef3d
Revises: f5c400194506
Create Date: 2023-09-06 10:21:13.451812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d28b3ebef3d'
down_revision = 'f5c400194506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('completion_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'completion_time')
    # ### end Alembic commands ###
