"""empty message

Revision ID: 3e4ed46ded9c
Revises: 3f1a548245a4
Create Date: 2023-07-26 13:07:30.555785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4ed46ded9c'
down_revision = '3f1a548245a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('company_user_user_ud_fkey', 'company_user', type_='foreignkey')
    op.create_foreign_key(None, 'company_user', 'users', ['user_id'], ['id'])
    op.drop_column('company_user', 'user_ud')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_user', sa.Column('user_ud', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company_user', type_='foreignkey')
    op.create_foreign_key('company_user_user_ud_fkey', 'company_user', 'users', ['user_ud'], ['id'])
    op.drop_column('company_user', 'user_id')
    # ### end Alembic commands ###
