"""initial m2m company_user setup

Revision ID: 3f1a548245a4
Revises: d7be60bbfa82
Create Date: 2023-07-25 22:10:41.809084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1a548245a4'
down_revision = 'd7be60bbfa82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_user',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_ud', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='roleenum'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_ud'], ['users.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'user_ud')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_user')
    # ### end Alembic commands ###
