"""altered unique constraint

Revision ID: 6331e3a14dfd
Revises: c081846c3cc6
Create Date: 2023-08-08 09:13:18.504361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6331e3a14dfd'
down_revision = 'c081846c3cc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###