"""added unique constraints

Revision ID: 69f4b7511384
Revises: d4dbf4b64865
Create Date: 2023-08-10 06:49:53.172750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f4b7511384'
down_revision = 'd4dbf4b64865'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_answear_uc', 'answears', ['title', 'question_id'])
    op.create_unique_constraint('_question_uc', 'questions', ['title', 'quizz_id'])
    op.create_unique_constraint('_quizz_uc', 'quizzes', ['title', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_quizz_uc', 'quizzes', type_='unique')
    op.drop_constraint('_question_uc', 'questions', type_='unique')
    op.drop_constraint('_answear_uc', 'answears', type_='unique')
    # ### end Alembic commands ###
