"""empty message

Revision ID: 7e49457d124b
Revises: 02758c395092
Create Date: 2023-07-20 14:04:20.366980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e49457d124b'
down_revision = '02758c395092'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth0_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth0_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
