"""add on delete constraint

Revision ID: 81b8061cf451
Revises: 3e4ed46ded9c
Create Date: 2023-07-27 12:16:45.216148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b8061cf451'
down_revision = '3e4ed46ded9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_user_company_id_fkey', 'company_user', type_='foreignkey')
    op.drop_constraint('company_user_user_id_fkey', 'company_user', type_='foreignkey')
    op.create_foreign_key(None, 'company_user', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'company_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_user', type_='foreignkey')
    op.drop_constraint(None, 'company_user', type_='foreignkey')
    op.create_foreign_key('company_user_user_id_fkey', 'company_user', 'users', ['user_id'], ['id'])
    op.create_foreign_key('company_user_company_id_fkey', 'company_user', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
