"""add score field to user models

Revision ID: b53241deb209
Revises: 3723ddb10db9
Create Date: 2023-09-11 20:21:51.173374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53241deb209'
down_revision = '3723ddb10db9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_user', sa.Column('average_score', sa.DECIMAL(), nullable=True))
    op.add_column('users', sa.Column('overall_avg_score', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'overall_avg_score')
    op.drop_column('company_user', 'average_score')
    # ### end Alembic commands ###
