"""made sender_id and receiver_id nullable

Revision ID: c081846c3cc6
Revises: a3fc57a13dd7
Create Date: 2023-08-08 07:11:17.386890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c081846c3cc6'
down_revision = 'a3fc57a13dd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_request', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company_request', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_request', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company_request', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
