"""rename model quizz to quiz

Revision ID: f5c400194506
Revises: 3241e9c56d19
Create Date: 2023-08-15 08:17:57.444225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c400194506'
down_revision = '3241e9c56d19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.drop_constraint('_question_uc', 'questions', type_='unique')
    op.create_unique_constraint('_question_uc', 'questions', ['title', 'quiz_id'])
    op.drop_constraint('questions_quizz_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_column('questions', 'quizz_id')
    op.drop_constraint('_quizz_uc', 'quizzes', type_='unique')
    op.create_unique_constraint('_quiz_uc', 'quizzes', ['title', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_quiz_uc', 'quizzes', type_='unique')
    op.create_unique_constraint('_quizz_uc', 'quizzes', ['title', 'company_id'])
    op.add_column('questions', sa.Column('quizz_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_quizz_id_fkey', 'questions', 'quizzes', ['quizz_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('_question_uc', 'questions', type_='unique')
    op.create_unique_constraint('_question_uc', 'questions', ['title', 'quizz_id'])
    op.drop_column('questions', 'quiz_id')
    # ### end Alembic commands ###
